### ISSUE TITLE
\ Backslash dont work :(

### ISSUE THREAD

**Issue by dominikuskoch** [BesoBerlin/Arduino-German-Keyboard#1]
Hallo,
danke für deine Arbeit.

Ich versuche stundenlang ein Backslash auszugeben. Leider klappt das nicht. Auch nicht mit deiner Bibliothek (auch wenn ich jetzt meine Ausgabe schon deutlich verständlicher in den Sketch schreiben kann - dank dir).

Ich benutze einen ProMicro Arduino Clone, und alles außer das / funktioniert problemlos.

lg Dominikus

**Comment by BesoBerlin** [comment]
Hallo @dominikuskoch 
danke für dein Feedback und entschuldige die späte Reaktion.
den Backslash habe ich doch glatt ignoriert... sollte jetzt eigentlich gehen! 
wäre schön, wenn du irgendwie Bescheid gibst, obs klappt (z.B. indem du den issue dann closest)

LG

**Comment by dominikuskoch** [comment]
Moin, Danke für die Hilfe.

Aber es funktioniert trotzdem nicht.

Du hast in Zeile 89 übrigens einen Einrückungsfehler im Python Code :)

Aus 
c:\windows\system32
wird leider 
c:ßwindowsßsystem32

was ja im Grunde schon mal dem deutschen Layout entspricht, es fehlt nur noch der KeyCode für die AltGr Taste... 

Vielleicht bekomme ich das mit keyboard.press() hin... 
Bin aber grade aufm Sprung, wenn ich ne Lösung finde poste ich das hier.

lg Dominikus

**Comment by BesoBerlin** [comment]
Ja genau so... überprüfe doch mal bitte die finish.ino Datei an der betroffenen Stelle. Eigentlich sollte dort

`  Keyboard.print("c:");
  Keyboard.press(KEY_RIGHT_ALT);
  Keyboard.print("ß");
  Keyboard.release(KEY_RIGHT_ALT);
  Keyboard.print("windows");  
  Keyboard.press(KEY_RIGHT_ALT);
  Keyboard.print("ß");
  Keyboard.release(KEY_RIGHT_ALT);
  Keyboard.print("system32");`

stehen... bei mir klappt es zumindest... wenn nicht schau doch mal bitte ob alle Zeilen richtig eingerückt sind (besonders da wo EINRÜCKEN kommentiert wurde)

**Comment by BesoBerlin** [comment]
oh.. nach dem Test mit einem Arduino ...lol... habe ih den Fehler doch in der Keyboard_DE Bibliothek gefunden... Ich bin gerade in der Uni und versuche das nebenbei zu fixen... 
Als Workaround müsstest du das "ß" an oben besagter Stelle per Hand mit "\\" ersetzen...
also:
Keyboard.press(KEY_RIGHT_ALT);
Keyboard.print("\\");
Keyboard.release(KEY_RIGHT_ALT);

Der Fehler ist in der Übersetzng des Zeichens "?" von US zu DE.. 
Danke erneut für den Report!

**Comment by BesoBerlin** [comment]
ok... jetzt passt es aber! Danke nochmal für den Hinweis...
Bitte lass mich wissen, ob es diesmal klappt!

Dennoch: wenn du den Backslash in den Arduino .ino Quelltext eingibst, dann schreibst du den aber mit zwei Backslashs oder?

also in deinem Quellcode müsste dann stehen:
Keyboard.print("c:\\\\windows\\\\system32");
oder? die Variante Keyboard.print("c:\windows\system32"); würde ja mit US Layout auch nicht [in jedem Fall] funktionieren...
LG Beso

**Comment by BesoBerlin** [comment]
hast du nochmal die zeit gefunden zu testen?

**Comment by dominikuskoch** [comment]
Hi,
Sorry das ich nichts von mir hab hören lassen. Mir ist der USB Anschluss
vom Arduino abgerissen und ich muss erst einen neuen bestellen.

Aus Kostengründen bestelle ich immer direkt in China und dann dauert der
Versand ziemlich lange (und da ich noch ein paar andere Projekte habe hab
ich noch nicht mal bestellt)

LG Dominkus

Am 26.11.2017 20:28 schrieb "g0ld3n80y" <notifications@github.com>:
